version: '3'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - EXCHANGE_API_URL=https://api.exchangerate-api.com/v4/latest
      - CACHE_EXPIRY=3600
    depends_on:
      - redis
  redis:
    image: "redis:alpine"
